### ISSUE TITLE
Setup cannot be performed

### ISSUE THREAD

**Issue by ygoe** [Alex079/vscode-avr-helper#17]
I have at least three problems with this extension.

My environment is a Windows 10 PC with Atmel Studio 7 already installed. My AVR code works in there. I use pyupdi to flash the chip, but not on this computer, it's for development only. So I have no flash tool here at all. Then I installed VS Code. I've already tried out PlatformIO which didn't understand my code and had errors in the AVR header files. Then I tried to follow another guide which failed. Now I'm trying out this extension.

I'd like to use VS Code for main coding instead of the buggy Atmel Studio UI. So far I haven't been successful. Looks like I'll need to keep working in Atmel Studio because nobody has managed to replace it.

First issue: In the initial setup procedure, I am required to provide the binary of a flash tool. It cannot be omitted and it has to be an existing file. So I gave it the "C:\Program Files (x86)\Atmel\Studio\7.0\shellutils\true.exe" program. Must be good enough.

Second issue: When I try to select a device type, there are none at all available, unlike the screen recording shown on the VS marketplace page. I need to select ATtiny1614 here. But that's not possible, nothing can be entered here.

Third issue: Tons of errors in the existing C++ code. I manually added the include path from the installed Atmel Studio but it didn't help. The undefined symbols include `EEMEM`, `uint8_t`, `uint16_t`, `eeprom_read_byte`, `PORTA`, `PORT_ISC_FALLING_gc` and many more. The compiler doesn't seem to know what AVR is. Isn't that the whole point of this extension?

More issues are inaccessible at this point but I'm sure they exist.

**Comment by Alex079** [comment]
Hello!

This extension needs avrdude programmer in order to discover supported devices. One can download avrdude along with the rest of avr-gcc toolchain for Windows. If avrdude tool is provided by Atmel Studio, this one should work as well.

Concerning why you experience this issue, there are the following considerations:
- avr-gcc alone does not provide (or at least I could not find any) way to extract supported MCU device list and their capabilities, I decided to use avrdude tool for everything device-related: MCU device list, programmer device list, device capabilities
- avrdude is shipped with a user-configurable device database, which can be tweaked as needed, and this makes it a good candidate for a lightweight yet customizable plugin like AVR Helper without any need to design and implement another device database

Please let me know if specifying the path to avrdude.exe solves your problem.
As another user reported in #16, you may (or may not) experience a problem with Makefile. There is a temporary fix for Makefile for Windows, you may want to apply it as well.

Regards,
Alex

**Comment by ygoe** [comment]
Cleaning up my mailbox of forgotten messages. I've moved to VSCode + Platform IO which works fine for AVR and ESP32 with no dependencies, so I don't need this anymore.
