### ISSUE TITLE
How to create .hex file in avr.targets.mk?

### ISSUE THREAD

**Issue by wanggaoteng** [Alex079/vscode-avr-helper#3]
Hi, I find that there are two files generated by:
```
A.elf := $(A.output.dir)/output.elf
A.list := $(A.output.dir)/output.lst
```
in avr.targets.mk file, can the .hex file be generated?
Best regards.

**Comment by Alex079** [comment]
Hi!
It is possible to dump one or many sections of ELF file into HEX file(s).
Do you think it is useful to produce HEX by default? I chose elf format over hex format for uploading in order to let avrdude decide how to map file sections.

Nevertheless.
The deleted part (as one can see in the file history) was something like
```
E.objcopy = $(A.compiler.dir)avr-objcopy -O ihex
E.make.text = $(E.objcopy) -j .text -j .data
E.make.eeprom = $(E.objcopy) -j .eeprom --set-section-flags=.eeprom=alloc,load --no-change-warnings --change-section-lma .eeprom=0
E.make.fuse = $(E.objcopy) -j .fuse --no-change-warnings --change-section-lma .fuse=0
E.make.lock = $(E.objcopy) -j .lock --no-change-warnings --change-section-lma .lock=0

$(A.text) : $(A.elf)
	@mkdir -p $(@D)
	$(info ===== Making $@)
	@$(E.make.text) $^ $@
	$(info )
```

In general, the command is `avr-objcopy -O ihex -j .text -j .data INPUT.elf RESULT.hex`

Regards
